version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=commerzbank-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ["-l", "9007199254740991", "--account=0x4c0883a69102937d6231471b5dbb6204fe512961708279dc6a5cceab47dfacf2,100000000000000000000"]
    ports:
      - 8545:8545
volumes:
  postgres_data: